# Generated by Django 6.0.4 on 2026-04-29 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО специалиста')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время начала (слот 2 часа)')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Занято клиентом')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='monitoring.specialist')),
            ],
        ),
    ]
