# Generated by Django 6.0.4 on 2026-05-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_appointmentslot_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('thermostat', 'GSM-термостат'), ('controller', 'Контроллер отопления'), ('tracker', 'Автомобильный трекер'), ('security', 'Охранная система')], max_length=50)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
