# Generated by Django 6.0.4 on 2026-04-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_specialist_appointmentslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='monitoring.supportticket', verbose_name='Связанная заявка'),
        ),
    ]
