# Generated by Django 6.0.4 on 2026-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_clientdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='last_metric',
            field=models.FloatField(blank=True, null=True, verbose_name='Последняя метрика'),
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='last_metric_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_metric',
            field=models.FloatField(blank=True, null=True, verbose_name='Последняя метрика'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_metric_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
