# Generated by Django 6.0.4 on 2026-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_clientdevice_last_metric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='max_temp',
            field=models.FloatField(default=30.0, verbose_name='Макс. норма (°C)'),
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='min_temp',
            field=models.FloatField(default=10.0, verbose_name='Мин. норма (°C)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_temp',
            field=models.FloatField(default=30.0, verbose_name='Макс. норма (°C)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_temp',
            field=models.FloatField(default=10.0, verbose_name='Мин. норма (°C)'),
        ),
    ]
